In [1]:
#Bringing in CSVs use in data compilation 
import pandas as pd
from sqlalchemy import create_engine, Column, Integer, String
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()
engine = create_engine('sqlite:///HappinessIndex.sqlite')
#Base.metadata.drop_all(engine)

In [18]:
from sqlalchemy import Float

In [2]:
#Reading in the World Happiness Report from 2021
happiness = pd.read_csv("Data/world-happiness-report-2021.csv")
happiness

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.000,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
1,Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.700,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868
2,Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.400,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839
3,Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.000,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967
4,Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.400,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,Lesotho,Sub-Saharan Africa,3.512,0.120,3.748,3.276,7.926,0.787,48.700,0.715,-0.131,0.915,2.43,0.451,0.731,0.007,0.405,0.103,0.015,1.800
145,Botswana,Sub-Saharan Africa,3.467,0.074,3.611,3.322,9.782,0.784,59.269,0.824,-0.246,0.801,2.43,1.099,0.724,0.340,0.539,0.027,0.088,0.648
146,Rwanda,Sub-Saharan Africa,3.415,0.068,3.548,3.282,7.676,0.552,61.400,0.897,0.061,0.167,2.43,0.364,0.202,0.407,0.627,0.227,0.493,1.095
147,Zimbabwe,Sub-Saharan Africa,3.145,0.058,3.259,3.030,7.943,0.750,56.201,0.677,-0.047,0.821,2.43,0.457,0.649,0.243,0.359,0.157,0.075,1.205
148,Afghanistan,South Asia,2.523,0.038,2.596,2.449,7.695,0.463,52.493,0.382,-0.102,0.924,2.43,0.370,0.000,0.126,0.000,0.122,0.010,1.895

In [3]:
#Reading in the ISO codes for each country
isocc = pd.read_csv("Data/iso-country-codes.csv")
isocc

          Country name Alpha-2 code Alpha-3 code  Numeric code     ISO 3166-2
0          Afghanistan           AF          AFG             4  ISO 3166-2:AF
1        Åland Islands           AX          ALA           248  ISO 3166-2:AX
2              Albania           AL          ALB             8  ISO 3166-2:AL
3              Algeria           DZ          DZA            12  ISO 3166-2:DZ
4       American Samoa           AS          ASM            16  ISO 3166-2:AS
..                 ...          ...          ...           ...            ...
241  Wallis and Futuna           WF          WLF           876  ISO 3166-2:WF
242     Western Sahara           EH          ESH           732  ISO 3166-2:EH
243              Yemen           YE          YEM           887  ISO 3166-2:YE
244             Zambia           ZM          ZMB           894  ISO 3166-2:ZM
245           Zimbabwe           ZW          ZWE           716  ISO 3166-2:ZW

[246 rows x 5 columns]

In [4]:
#Combining the World Happiness Report & the ISOs 
Happiness_ISO = pd.merge(left=happiness,right=isocc, left_on='Country name', right_on='Country name')
Happiness_ISO.shape
Happiness_ISO

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual,Alpha-2 code,Alpha-3 code,Numeric code,ISO 3166-2
0,Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.000,0.949,...,1.106,0.741,0.691,0.124,0.481,3.253,FI,FIN,246,ISO 3166-2:FI
1,Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.700,0.946,...,1.108,0.763,0.686,0.208,0.485,2.868,DK,DNK,208,ISO 3166-2:DK
2,Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.400,0.919,...,1.079,0.816,0.653,0.204,0.413,2.839,CH,CHE,756,ISO 3166-2:CH
3,Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.000,0.955,...,1.172,0.772,0.698,0.293,0.170,2.967,IS,ISL,352,ISO 3166-2:IS
4,Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.400,0.913,...,1.079,0.753,0.647,0.302,0.384,2.798,NL,NLD,528,ISO 3166-2:NL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,Lesotho,Sub-Saharan Africa,3.512,0.120,3.748,3.276,7.926,0.787,48.700,0.715,...,0.731,0.007,0.405,0.103,0.015,1.800,LS,LSO,426,ISO 3166-2:LS
131,Botswana,Sub-Saharan Africa,3.467,0.074,3.611,3.322,9.782,0.784,59.269,0.824,...,0.724,0.340,0.539,0.027,0.088,0.648,BW,BWA,72,ISO 3166-2:BW
132,Rwanda,Sub-Saharan Africa,3.415,0.068,3.548,3.282,7.676,0.552,61.400,0.897,...,0.202,0.407,0.627,0.227,0.493,1.095,RW,RWA,646,ISO 3166-2:RW
133,Zimbabwe,Sub-Saharan Africa,3.145,0.058,3.259,3.030,7.943,0.750,56.201,0.677,...,0.649,0.243,0.359,0.157,0.075,1.205,ZW,ZWE,716,ISO 3166-2:ZW
134,Afghanistan,South Asia,2.523,0.038,2.596,2.449,7.695,0.463,52.493,0.382,...,0.000,0.126,0.000,0.122,0.010,1.895,AF,AFG,4,ISO 3166-2:AF

In [5]:
#Dropping the 2 code, ISO#, & numberic codes since those aren't needed to combine with our data

Happiness_ISO.drop(['Regional indicator','Alpha-2 code', 'Numeric code','ISO 3166-2','Standard error of ladder score','upperwhisker','lowerwhisker'], axis='columns', inplace=True)
Happiness_ISO

,Country name,Ladder score,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual,Alpha-3 code
0,Finland,7.842,10.775,0.954,72.000,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253,FIN
1,Denmark,7.620,10.933,0.954,72.700,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868,DNK
2,Switzerland,7.571,11.117,0.942,74.400,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839,CHE
3,Iceland,7.554,10.878,0.983,73.000,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967,ISL
4,Netherlands,7.464,10.932,0.942,72.400,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798,NLD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,Lesotho,3.512,7.926,0.787,48.700,0.715,-0.131,0.915,2.43,0.451,0.731,0.007,0.405,0.103,0.015,1.800,LSO
131,Botswana,3.467,9.782,0.784,59.269,0.824,-0.246,0.801,2.43,1.099,0.724,0.340,0.539,0.027,0.088,0.648,BWA
132,Rwanda,3.415,7.676,0.552,61.400,0.897,0.061,0.167,2.43,0.364,0.202,0.407,0.627,0.227,0.493,1.095,RWA
133,Zimbabwe,3.145,7.943,0.750,56.201,0.677,-0.047,0.821,2.43,0.457,0.649,0.243,0.359,0.157,0.075,1.205,ZWE
134,Afghanistan,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,2.43,0.370,0.000,0.126,0.000,0.122,0.010,1.895,AFG

In [6]:
Happiness_ISO = Happiness_ISO.rename(columns={'Alpha-3 code': 'country_code'})
Happiness_ISO.set_index('country_code', inplace=True)
Happiness_ISO

,Country name,Ladder score,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
country_code,,,,,,,,,,,,,,,,
FIN,Finland,7.842,10.775,0.954,72.000,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
DNK,Denmark,7.620,10.933,0.954,72.700,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868
CHE,Switzerland,7.571,11.117,0.942,74.400,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839
ISL,Iceland,7.554,10.878,0.983,73.000,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967
NLD,Netherlands,7.464,10.932,0.942,72.400,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
LSO,Lesotho,3.512,7.926,0.787,48.700,0.715,-0.131,0.915,2.43,0.451,0.731,0.007,0.405,0.103,0.015,1.800
BWA,Botswana,3.467,9.782,0.784,59.269,0.824,-0.246,0.801,2.43,1.099,0.724,0.340,0.539,0.027,0.088,0.648
RWA,Rwanda,3.415,7.676,0.552,61.400,0.897,0.061,0.167,2.43,0.364,0.202,0.407,0.627,0.227,0.493,1.095
ZWE,Zimbabwe,3.145,7.943,0.750,56.201,0.677,-0.047,0.821,2.43,0.457,0.649,0.243,0.359,0.157,0.075,1.205
AFG,Afghanistan,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,2.43,0.370,0.000,0.126,0.000,0.122,0.010,1.895

In [13]:
#During discussions we decided that we didn't need all of the Happiness Report data along with the alpha-3 because we are using it for joining table. Ugly & inefficient, but we go there.
countries_df=Happiness_ISO.drop(['Ladder score', 'Logged GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption', 'Ladder score in Dystopia', 'Explained by: Log GDP per capita', 'Explained by: Social support', 'Explained by: Healthy life expectancy', 'Explained by: Freedom to make life choices', 'Explained by: Generosity', 'Explained by: Perceptions of corruption', 'Dystopia + residual'], axis='columns')
countries_df.rename(columns={'Country name':'country_name'}, inplace=True)
countries_df

             country_name
country_code
FIN               Finland
DNK               Denmark
CHE           Switzerland
ISL               Iceland
NLD           Netherlands
...                   ...
LSO               Lesotho
BWA              Botswana
RWA                Rwanda
ZWE              Zimbabwe
AFG           Afghanistan

[135 rows x 1 columns]

In [23]:
Happiness_Index=Happiness_ISO.drop(['Country name'], axis='columns')
Happiness_Index.rename(columns={'Dystopia + residual':'Dystopia_residual','Explained by: Log GDP per capita':'Explained by Log GDP per capita','Explained by: Social support':'Explained by Social support','Explained by: Healthy life expectancy':'Explained by Healthy life expectancy','Explained by: Freedom to make life choices':'Explained by Freedom to make life choices','Explained by: Generosity':'Explained by Generosity','Explained by: Perceptions of corruption':'Explained by Perceptions of corruption'}, inplace=True)
Happiness_Index

,Ladder score,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by Log GDP per capita,Explained by Social support,Explained by Healthy life expectancy,Explained by Freedom to make life choices,Explained by Generosity,Explained by Perceptions of corruption,Dystopia_residual
country_code,,,,,,,,,,,,,,,
FIN,7.842,10.775,0.954,72.000,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
DNK,7.620,10.933,0.954,72.700,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868
CHE,7.571,11.117,0.942,74.400,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839
ISL,7.554,10.878,0.983,73.000,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967
NLD,7.464,10.932,0.942,72.400,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
LSO,3.512,7.926,0.787,48.700,0.715,-0.131,0.915,2.43,0.451,0.731,0.007,0.405,0.103,0.015,1.800
BWA,3.467,9.782,0.784,59.269,0.824,-0.246,0.801,2.43,1.099,0.724,0.340,0.539,0.027,0.088,0.648
RWA,3.415,7.676,0.552,61.400,0.897,0.061,0.167,2.43,0.364,0.202,0.407,0.627,0.227,0.493,1.095
ZWE,3.145,7.943,0.750,56.201,0.677,-0.047,0.821,2.43,0.457,0.649,0.243,0.359,0.157,0.075,1.205
AFG,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,2.43,0.370,0.000,0.126,0.000,0.122,0.010,1.895

In [ ]:
#A CSV of the original Happiness Report + ISO was created called Happiness_Report_ISO but that won't be used. 
Happiness_ISO.to_csv('Country_with_ISO.csv')

In [8]:
# Define our country table
class HappinessIndex(Base):
    __tablename__ = 'countries'
    __table_args__ = {'extend_existing': True}
    country_code = Column(String, primary_key=True)
    country_name = Column(String)

In [25]:
class Happiness_Index(Base):
    __tablename__ = 'Happiness_Index'
    __table_args__ = {'extend_existing': True}
    country_code = Column(String, primary_key=True)
    Ladder_score = Column(String)
    Logged_GDP_per_capita = Column(Float)
    Social_support = Column(Float)
    Healthy_life_expectancy = Column(Float)
    Freedom_to_make_life_choices = Column(Float)
    Generosity = Column(Float)
    Perceptions_of_corruption = Column(Float)
    Ladder_score_in_Dystopia = Column(Float)
    Explained_by_Log_GDP_per_capita = Column(Float)
    Explained_by_Social_support = Column(Float)
    Explained_by_Healthy_life_expectancy = Column(Float)
    Explained_by_Freedom_to_make_life_choices = Column(Float)
    Explained_by_Generosity = Column(Float)
    Explained_by_Perceptions_of_corruption = Column(Float)
    Dystopia_residual = Column(Float)

In [26]:
Base.metadata.tables

FacadeDict({'countries': Table('countries', MetaData(), Column('country_code', String(), table=<countries>, primary_key=True, nullable=False), Column('country_name', String(), table=<countries>), schema=None), 'Happiness_Index': Table('Happiness_Index', MetaData(), Column('country_code', String(), table=<Happiness_Index>, primary_key=True, nullable=False), Column('Ladder_score', String(), table=<Happiness_Index>), Column('Logged_GDP_per_capita', Float(), table=<Happiness_Index>), Column('Social_support', Float(), table=<Happiness_Index>), Column('Healthy_life_expectancy', Float(), table=<Happiness_Index>), Column('Freedom_to_make_life_choices', Float(), table=<Happiness_Index>), Column('Generosity', Float(), table=<Happiness_Index>), Column('Perceptions_of_corruption', Float(), table=<Happiness_Index>), Column('Ladder_score_in_Dystopia', Float(), table=<Happiness_Index>), Column('Explained_by_Log_GDP_per_capita', Float(), table=<Happiness_Index>), Column('Explained_by_Social_support', Float(), table=<Happiness_Index>), Column('Explained_by_Healthy_life_expectancy', Float(), table=<Happiness_Index>), Column('Explained_by_Freedom_to_make_life_choices', Float(), table=<Happiness_Index>), Column('Explained_by_Generosity', Float(), table=<Happiness_Index>), Column('Explained_by_Perceptions_of_corruption', Float(), table=<Happiness_Index>), Column('Dystopia_residual', Float(), table=<Happiness_Index>), schema=None)})

In [27]:
Base.metadata.create_all(engine)

In [28]:
countries_df.to_sql('countries',engine, if_exists='append')
#pandas.DataFrame.to_sql(table_name, engine_name, if_exists, schema, index, chunksize, dtype)

IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: countries.country_code
[SQL: INSERT INTO countries (country_code, country_name) VALUES (?, ?)]
[parameters: (('FIN', 'Finland'), ('DNK', 'Denmark'), ('CHE', 'Switzerland'), ('ISL', 'Iceland'), ('NLD', 'Netherlands'), ('NOR', 'Norway'), ('SWE', 'Sweden'), ('LUX', 'Luxembourg')  ... displaying 10 of 135 total bound parameter sets ...  ('ZWE', 'Zimbabwe'), ('AFG', 'Afghanistan'))]
(Background on this error at: https://sqlalche.me/e/14/gkpj)

In [29]:
Happiness_Index.to_sql('Happiness_Index',engine, if_exists='append')

AttributeError: type object 'Happiness_Index' has no attribute 'to_sql'